# Generated by Django 3.2.14 on 2022-07-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclass',
            name='a',
            field=models.ImageField(upload_to=''),
        ),
    ]
