# Generated by Django 3.2.14 on 2022-07-11 10:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_myclass_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myclass',
            name='a',
        ),
        migrations.AddField(
            model_name='myclass',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='img/'),
            preserve_default=False,
        ),
    ]
