# Generated by Django 3.2.14 on 2022-07-12 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_rename_photo_myclass'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='myClass',
            new_name='Photo',
        ),
    ]
