# Generated by Django 3.2.14 on 2022-07-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_alter_experiment_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecording',
            name='video_description',
            field=models.TextField(default='no description'),
        ),
        migrations.AddField(
            model_name='videorecording',
            name='video_duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
