# Generated by Django 3.2.14 on 2022-07-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_auto_20220713_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='path',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='result_path',
            field=models.URLField(),
        ),
    ]
