# Generated by Django 3.2.14 on 2022-07-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_alter_experiment_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecording',
            name='video_file',
            field=models.FileField(default=1, upload_to='exp<django.db.models.fields.related.ForeignKey>'),
            preserve_default=False,
        ),
    ]
