# Generated by Django 3.2.14 on 2022-07-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0018_alter_experiment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='description',
            field=models.TextField(default='no description', null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='path',
            field=models.URLField(null=True, verbose_name='exp<django.db.models.fields.AutoField>'),
        ),
    ]
