# Generated by Django 3.2.14 on 2022-07-14 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0019_auto_20220714_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='animal_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.animal'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='count_irradiated',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='count_unirradiated',
            field=models.IntegerField(null=True),
        ),
    ]
