# Generated by Django 3.2.14 on 2022-07-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0022_alter_videorecording_video_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecording',
            name='url',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
