# Generated by Django 3.2.14 on 2022-07-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0023_videorecording_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videorecording',
            name='video_file',
            field=models.FileField(upload_to='Experiment_<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
