# Generated by Django 3.2.14 on 2022-07-15 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0025_alter_result_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videorecording',
            name='video_duration',
        ),
    ]
