# Generated by Django 3.2.14 on 2022-07-15 10:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0026_remove_videorecording_video_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='animal_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myApp.animal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experiment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='description',
            field=models.TextField(default='no description'),
        ),
    ]
