# Generated by Django 3.2.14 on 2022-07-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0027_auto_20220715_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorecording',
            name='animal_irradiated',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
