# Generated by Django 3.2.14 on 2022-07-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0028_videorecording_animal_irradiated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videorecording',
            name='animal_irradiated',
            field=models.BooleanField(null=True),
        ),
    ]
