# Generated by Django 3.2.14 on 2022-07-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0029_alter_videorecording_animal_irradiated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment',
            old_name='date',
            new_name='experiment_date',
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='description',
            new_name='experiment_description',
        ),
        migrations.RenameField(
            model_name='experiment',
            old_name='name',
            new_name='experiment_name',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='count_irradiated',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='count_unirradiated',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='path',
        ),
        migrations.AddField(
            model_name='experiment',
            name='count_irradiated_animals',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='count_unirradiated_animals',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='experiment_path',
            field=models.URLField(default=1, verbose_name='exp<django.db.models.fields.AutoField>'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experiment',
            name='time_after_experiment',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
