# Generated by Django 3.2.14 on 2022-07-18 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0030_auto_20220718_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videorecording',
            old_name='url',
            new_name='video_url',
        ),
        migrations.RemoveField(
            model_name='videorecording',
            name='video_file',
        ),
    ]
